namespace CSharpRPGBackend.Core;

/// <summary>
/// Represents a quest in the game world.
/// </summary>
public class Quest
{
    public string Id { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string GiverNpcId { get; set; } = string.Empty;
    public QuestStatus Status { get; set; } = QuestStatus.Offered;

    /// <summary>
    /// The type of quest (story, job, crafting order, etc.).
    /// </summary>
    public QuestType Type { get; set; } = QuestType.SideQuest;

    /// <summary>
    /// Whether this quest can be repeated after completion.
    /// </summary>
    public bool IsRepeatable { get; set; } = false;

    /// <summary>
    /// Whether this quest was dynamically generated by the GM.
    /// </summary>
    public bool IsDynamic { get; set; } = false;

    /// <summary>
    /// Structured requirements to complete this quest.
    /// </summary>
    public List<QuestRequirement> Requirements { get; set; } = new();

    /// <summary>
    /// Structured rewards for completing this quest.
    /// </summary>
    public QuestRewards Rewards { get; set; } = new();

    // Legacy fields for backward compatibility
    public int RewardExperience { get => Rewards.Experience; set => Rewards.Experience = value; }
    public int RewardGold { get => (int)Rewards.Currency; set => Rewards.Currency = value; }

    /// <summary>
    /// Text-based objectives (legacy, use Requirements for structured tracking).
    /// </summary>
    public List<string> Objectives { get; set; } = new();
    public List<string> CompletedObjectives { get; set; } = new();

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// For crafting orders: the item being requested.
    /// </summary>
    public string? RequestedItemId { get; set; }
    public int RequestedQuantity { get; set; } = 1;

    /// <summary>
    /// Optional dialogue when quest is offered.
    /// </summary>
    public string? OfferDialogue { get; set; }

    /// <summary>
    /// Optional dialogue when quest is completed.
    /// </summary>
    public string? CompletionDialogue { get; set; }

    /// <summary>
    /// Check if all requirements are met (for structured quests).
    /// </summary>
    public bool AreRequirementsMet(QuestProgress progress)
    {
        if (Requirements.Count == 0)
            return CompletedObjectives.Count == Objectives.Count;

        foreach (var req in Requirements)
        {
            if (!progress.IsRequirementMet(req))
                return false;
        }
        return true;
    }

    public bool IsComplete => CompletedObjectives.Count == Objectives.Count ||
                              (Requirements.Count > 0 && Requirements.All(r => r.IsMet));
}

/// <summary>
/// Type of quest.
/// </summary>
public enum QuestType
{
    /// <summary>Main storyline quests.</summary>
    Story,
    
    /// <summary>Optional side quests from NPCs.</summary>
    SideQuest,
    
    /// <summary>Repeatable tasks (gather items, deliver packages).</summary>
    Job,
    
    /// <summary>NPC wants you to craft or obtain a specific item.</summary>
    CraftingOrder,
    
    /// <summary>Kill or defeat specific enemies.</summary>
    Bounty,
    
    /// <summary>Protect or escort an NPC to a destination.</summary>
    Escort,
    
    /// <summary>Discover a location or explore an area.</summary>
    Exploration,
    
    /// <summary>Deliver an item from one NPC to another.</summary>
    Delivery
}

public enum QuestStatus
{
    Offered,
    Accepted,
    InProgress,
    Completed,
    Failed,
    TurnedIn
}

/// <summary>
/// A specific requirement to complete a quest.
/// </summary>
public class QuestRequirement
{
    /// <summary>
    /// Type of requirement: "item", "kill", "location", "talk", "craft", "gather"
    /// </summary>
    public string Type { get; set; } = "item";

    /// <summary>
    /// The target ID (item ID, NPC ID, room ID, etc.).
    /// </summary>
    public string TargetId { get; set; } = string.Empty;

    /// <summary>
    /// Display name for the requirement.
    /// </summary>
    public string? TargetName { get; set; }

    /// <summary>
    /// Quantity needed (for items, kills, etc.).
    /// </summary>
    public int Quantity { get; set; } = 1;

    /// <summary>
    /// Current progress toward this requirement.
    /// </summary>
    public int CurrentProgress { get; set; } = 0;

    /// <summary>
    /// Whether items are consumed when quest is completed.
    /// </summary>
    public bool ConsumedOnCompletion { get; set; } = true;

    /// <summary>
    /// Optional description of this requirement.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Whether this requirement is met.
    /// </summary>
    public bool IsMet => CurrentProgress >= Quantity;

    /// <summary>
    /// Get display text for this requirement.
    /// </summary>
    public string GetDisplayText()
    {
        var name = TargetName ?? TargetId;
        return Type switch
        {
            "item" => $"Obtain {name} ({CurrentProgress}/{Quantity})",
            "kill" => $"Defeat {name} ({CurrentProgress}/{Quantity})",
            "location" => IsMet ? $"✓ Visit {name}" : $"Visit {name}",
            "talk" => IsMet ? $"✓ Talk to {name}" : $"Talk to {name}",
            "gather" => $"Gather {name} ({CurrentProgress}/{Quantity})",
            "craft" => $"Craft {name} ({CurrentProgress}/{Quantity})",
            _ => Description ?? $"{Type}: {name}"
        };
    }
}

/// <summary>
/// Rewards for completing a quest.
/// </summary>
public class QuestRewards
{
    public int Experience { get; set; } = 0;
    public long Currency { get; set; } = 0;
    
    /// <summary>
    /// Items rewarded (ItemId, Quantity).
    /// </summary>
    public List<(string ItemId, int Quantity)> Items { get; set; } = new();
    
    /// <summary>
    /// Reputation changes with factions (FactionId, Change).
    /// </summary>
    public Dictionary<string, int> ReputationChanges { get; set; } = new();

    /// <summary>
    /// Recipe IDs that are learned upon completion.
    /// </summary>
    public List<string> RecipesLearned { get; set; } = new();
}

/// <summary>
/// Tracks progress for active quests.
/// </summary>
public class QuestProgress
{
    public string QuestId { get; set; } = string.Empty;
    
    /// <summary>
    /// Progress for each requirement (requirement index -> progress).
    /// </summary>
    public Dictionary<int, int> RequirementProgress { get; set; } = new();

    /// <summary>
    /// Items collected for this quest (ItemId -> Quantity).
    /// </summary>
    public Dictionary<string, int> CollectedItems { get; set; } = new();

    /// <summary>
    /// NPCs killed/defeated for this quest (NpcId -> Count).
    /// </summary>
    public Dictionary<string, int> KillCounts { get; set; } = new();

    /// <summary>
    /// Locations visited for this quest.
    /// </summary>
    public HashSet<string> VisitedLocations { get; set; } = new();

    public bool IsRequirementMet(QuestRequirement req)
    {
        return req.Type switch
        {
            "item" => CollectedItems.GetValueOrDefault(req.TargetId, 0) >= req.Quantity,
            "kill" => KillCounts.GetValueOrDefault(req.TargetId, 0) >= req.Quantity,
            "location" => VisitedLocations.Contains(req.TargetId),
            "gather" => CollectedItems.GetValueOrDefault(req.TargetId, 0) >= req.Quantity,
            _ => req.CurrentProgress >= req.Quantity
        };
    }
}

